# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestDefaultSuite:
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        # self.driver.quit()
        pass

    def test_testsearch(self):
        self.driver.get("https://testerhome.com/")
        self.driver.set_window_size(1200, 1200)
        WebDriverWait(self.driver, 10).until(expected_conditions.element_to_be_clickable((By.CSS_SELECTOR, '#main-nav-menu > ul > li:nth-child(4) > a')))
        self.driver.find_element(By.CSS_SELECTOR, '#main-nav-menu > ul > li:nth-child(4) > a').click()
        WebDriverWait(self.driver, 10).until(expected_conditions.element_to_be_clickable((By.CSS_SELECTOR, '.team-name[href="/hogwarts"]')))
        self.driver.find_element(By.CSS_SELECTOR, '.team-name[href="/hogwarts"]').click()
        WebDriverWait(self.driver, 10).until(expected_conditions.element_to_be_clickable((By.CSS_SELECTOR, '.nav.nav-tabs.team-menu > li:nth-child(2) a')))
        self.driver.find_element(By.CSS_SELECTOR, '.nav.nav-tabs.team-menu > li:nth-child(2) a').click()


"""
class TestTesterHome:

    def setup_method(self):
        self.driver = webdriver.Chrome()
        self.driver.implicitly_wait(10)
        self.driver.get('https://testerhome.com/')

    def teardown_method(self):
        time.sleep(10)
        self.driver.quit()

    def test_mainpage(self):
        self.driver.find_element(By.CSS_SELECTOR, '#main-nav-menu > ul > li:nth-child(4) > a').click()
        time.sleep(10)
        self.driver.find_element(By.CSS_SELECTOR,
                                 'div.panel-body > div > div:nth-child(1) > div > div.media-body > div.media-heading > a').click()
        time.sleep(10)
        self.driver.find_element(By.CSS_SELECTOR,
                                 'div.panel-body > div:nth-child(1) > div.infos.media-body > div.title.media-heading > a').click()
"""
